### ISSUE TITLE
Expand provider list

### ISSUE THREAD

**Issue by ipfaffy** [KeizerDev/domainchecker#3]
I'd love to see some more providers available. Off the top of my head I can think of Google Domains, Enom, and Gandi.net.

**Comment by KeizerDev** [comment]
I've some trouble with providers who only use post requests like gandy.net does. I'll get to this issue on Sunday, don't have much time now.

**Comment by KeizerDev** [comment]
Google Domains(https://domains.google.com/registrar?s=) and eNom(http://www.enom.com/domainsearch/search-results.aspx?sld=domain&searchedDomain=domain.nl) will be implemented tomorrow.

**Comment by KeizerDev** [comment]
Google Domains: 

```
$ domainchecker mydomain.org -p googledomains
```

eNom: 

```
$ domainchecker mydomain.org -p enom
```
